version: '3.4'

services:
  httpd:
    build:
      context: .
      target: local_httpd
      args:
        - USER_ID=1000
        - GROUP_ID=1000
        - XDEBUG_CLIENT_HOST=host.docker.internal
        - XDEBUG_CLIENT_PORT=9003
    ports:
      - 8080:8080
    volumes:
      - ./public:/usr/local/apache2/htdocs
      - .:/app/httpd
    command: sh -c 'httpd-foreground'